# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S0a1ZTzBAbVixtVEzxfU981SSvGDczXj
"""

def decimal_to_binary(decimal_num):
    binary_num = ""
    while decimal_num > 0:
        remainder = decimal_num % 2
        binary_num = str(remainder) + binary_num
        decimal_num //= 2
    return binary_num

def decimal_to_hex(decimal_num):
    hex_chars = "0123456789ABCDEF"
    hex_num = ""
    while decimal_num > 0:
        remainder = decimal_num % 16
        hex_num = hex_chars[remainder] + hex_num
        decimal_num //= 16
    return hex_num

def main():
    decimal_num = int(input("請輸入一個十進位數字："))
    binary_num = decimal_to_binary(decimal_num)
    hex_num = decimal_to_hex(decimal_num)
    print("十進位數字", decimal_num, "的二進位為：", binary_num)
    print("十進位數字", decimal_num, "的十六進位為：", hex_num)

if __name__ == "__main__":
    main()